### PR TITLE
Libmaxminddb support

### PR DESCRIPTION
**Pull request by Mank16**
Hi, please include this changes someday.
libmaxminddb (aka GeoIP v2) support instead of legacy geoip (wich would be since April 2018 not updated anymore)
more info here 
https://dev.maxmind.com/geoip/geoip2/geolite2/
did not removed geoiplib files.. they can be removed latter
and also GeoIP.cpp and h is not needed. same as above. instead is used cmaxminddb.cpp/h files.
unless i forgot somewhere something all should work.
Did not fully test changes in UpdateManager, but they should work. (needed some check how do this properly) maxminddb does not need diff versions for IPv4 and Ipv6. thats all.
thanx for considering it.

### CODE REVIEW

**Comment by maksis** [comment]
Thanks - such migration is definitely needed.

I noticed that the [changes you made in BMDC++](http://bazaar.launchpad.net/~manky/bmdc++/trunk/revision/963) are quite different from this pull request (there are no cmaxminddb files). What made you choose different approach there?

**Comment by Mank16** [comment]
@maksis well these changes are similiar. just both wroten in a little bit diff time. and BMDCs changes dont count with all possible things yet. nothing realy realy important in these diff versions of it.

**Comment by maksis** [comment]
What do you think of https://github.com/airdcpp/airgit/commit/ca9d21b818e7991f2c38f5932e3942081d0d2ce5 ?

It effectively combines the code from this pull request and BMDC (`SETTING(COUNTRY_FORMAT)` is being respected, old GeoIP files are now using maxminddb). I also committed libmaxminddb directly into this repository.

**Comment by Mank16** [comment]
it look fine  for me. Only you *might* want on on other that english translate/locale of client use for name-country things their localization (maxminddb support only (beside en) , de (germany) , fr (french) , es (spain) , ru (russia), pt-Br (portugal i think), ja (Japan) and zh-CN (china)) at name variable ( that one i did not get to pull req. nor to BMDC. but since BMDC does not have a full translate to anything else that eng....). just letting know there is some option  people from other country/or these wich use client in diff locale / language that english. thats all.

**Comment by maksis** [comment]
> Only you might want on on other that english translate/locale of client use for name-country things their localization

Now implemented in https://github.com/airdcpp/airgit/commit/766177cf2348ea68b427ae55ed04d5a93e637fa0

**Pull request closed without merging**
